server:
  port: 8080
  servlet:
    context-path: /ms-gestion-banca/v1

logging:
  level:
    root: INFO

spring:
  application:
    name: ms-gestion-banca-v1
  data:
    mongodb:
      user: admin
      password: admin
      uri: mongodb://admin:admin@servermongodb:27017/Bank?authSource=admin
      #uri: mongodb://localhost:27017/Bank
